comment: false

coverage:
  range: 50..90
  round: up
  precision: 3

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

fixes:
  - "C:\\Users\\runneradmin\\project::"  # Adjusts paths on Windows
  - "/home/ubuntu/::"                    # Adjusts paths on Ubuntu
  - "/Users/runner/project::"             # Adjusts paths on macOS

file_exclude:
  - "*.yaml"
  - "*.yml"

codecov:
  require_ci_to_pass: yes
  after_n_builds: 3
