on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test-coverage

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-20.04,   r: 'release'}

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
           python-version: 3.9

      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.9

      - uses: r-lib/actions/setup-r@v2-branch
        with:
#          r-version: 'release'
          r-version: '4.3'

      - uses: r-lib/actions/setup-pandoc@v2-branch

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
#          pip install torch==1.8.0 -f https://download.pytorch.org/whl/torch_stable.html
#          pip install transformers==4.12.5

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-4.0-2-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-4.0-2-

      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr", dependencies = TRUE)
          remotes::install_cran("ggwordcloud")
        shell: Rscript {0}

      - name: Test coverage
        env:
          OMP_MAX_ACTIVE_LEVELS: 0
        run: covr::codecov()
        shell: Rscript {0}
