on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CODECOV

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-20.04,   r: 'release'}

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_DEBUG: true

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2-branch
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@v2-branch

      - name: Install System Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install and Verify talk Package from GitHub
        run: |
          install.packages("devtools", repos = "https://cloud.r-project.org")
          devtools::install_github("theharmonylab/talk")
          library(talk)
        shell: Rscript {0}

      - name: Verify Installed Package Files
        run: ls -R /Users/runner/work/talk/talk

      - name: Run Code Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          covr::codecov(
            token = Sys.getenv("CODECOV_TOKEN")
          )
        shell: Rscript {0}

      - name: List Files for Debugging
        run: ls -R
